# Generated by Django 4.1.9 on 2023-05-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_user_otps'),
    ]

    operations = [
        migrations.CreateModel(
            name='stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('open', models.BooleanField(default=False)),
                ('graph', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
        ),
    ]
